version: "3.9"

volumes:
  postgres-volume:

services:
  postgres:
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/bitnami/postgresql
